-- 1. Create the table to store classification history
CREATE TABLE
    public.classification_history (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        created_at TIMESTAMPTZ DEFAULT NOW () NOT NULL,
        user_id UUID REFERENCES public.profiles (id) ON DELETE CASCADE NOT NULL,
        image_url TEXT,
        result JSONB,
        accuracy REAL
    );

-- 2. Enable Row Level Security (RLS) on the new table
ALTER TABLE public.classification_history ENABLE ROW LEVEL SECURITY;

-- 3. Create a policy that allows users to view their own history
CREATE POLICY "Users can view their own classification history" ON public.classification_history FOR
SELECT
    TO authenticated USING (auth.uid () = user_id);

-- 4. Create a policy that allows users to insert their own history
CREATE POLICY "Users can insert their own classification history" ON public.classification_history FOR INSERT TO authenticated
WITH
    CHECK (auth.uid () = user_id);

-- 5. Grant all permissions to the service_role key (for admin tasks if needed)
GRANT ALL ON TABLE public.classification_history TO service_role;